name: "Hello world workflow"

# Controls when the action will run. Triggers the workflow on push sone to master or production branch.
on:
  push:
   branches:
   - master
   - production

jobs:
  hello_word:
    runs-on:
    steps:
      - name:"Print hello world"
        run: echo "hello_world"